// Code generated by ent, DO NOT EDIT.

package game

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the game type in the database.
	Label = "game"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHomeScore holds the string denoting the homescore field in the database.
	FieldHomeScore = "home_score"
	// FieldAwayScore holds the string denoting the awayscore field in the database.
	FieldAwayScore = "away_score"
	// EdgeAwayTeam holds the string denoting the awayteam edge name in mutations.
	EdgeAwayTeam = "awayTeam"
	// EdgeHomeTeam holds the string denoting the hometeam edge name in mutations.
	EdgeHomeTeam = "homeTeam"
	// EdgeSkaterStats holds the string denoting the skaterstats edge name in mutations.
	EdgeSkaterStats = "skaterStats"
	// EdgeGoalieStats holds the string denoting the goaliestats edge name in mutations.
	EdgeGoalieStats = "goalieStats"
	// Table holds the table name of the game in the database.
	Table = "games"
	// AwayTeamTable is the table that holds the awayTeam relation/edge.
	AwayTeamTable = "games"
	// AwayTeamInverseTable is the table name for the Team entity.
	// It exists in this package in order to avoid circular dependency with the "team" package.
	AwayTeamInverseTable = "teams"
	// AwayTeamColumn is the table column denoting the awayTeam relation/edge.
	AwayTeamColumn = "team_away_games"
	// HomeTeamTable is the table that holds the homeTeam relation/edge.
	HomeTeamTable = "games"
	// HomeTeamInverseTable is the table name for the Team entity.
	// It exists in this package in order to avoid circular dependency with the "team" package.
	HomeTeamInverseTable = "teams"
	// HomeTeamColumn is the table column denoting the homeTeam relation/edge.
	HomeTeamColumn = "team_home_games"
	// SkaterStatsTable is the table that holds the skaterStats relation/edge.
	SkaterStatsTable = "skater_stats"
	// SkaterStatsInverseTable is the table name for the SkaterStats entity.
	// It exists in this package in order to avoid circular dependency with the "skaterstats" package.
	SkaterStatsInverseTable = "skater_stats"
	// SkaterStatsColumn is the table column denoting the skaterStats relation/edge.
	SkaterStatsColumn = "game_skater_stats"
	// GoalieStatsTable is the table that holds the goalieStats relation/edge. The primary key declared below.
	GoalieStatsTable = "game_goalieStats"
	// GoalieStatsInverseTable is the table name for the GoalieStats entity.
	// It exists in this package in order to avoid circular dependency with the "goaliestats" package.
	GoalieStatsInverseTable = "goalie_stats"
)

// Columns holds all SQL columns for game fields.
var Columns = []string{
	FieldID,
	FieldHomeScore,
	FieldAwayScore,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "games"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"team_home_games",
	"team_away_games",
}

var (
	// GoalieStatsPrimaryKey and GoalieStatsColumn2 are the table columns denoting the
	// primary key for the goalieStats relation (M2M).
	GoalieStatsPrimaryKey = []string{"game_id", "goalie_stats_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the Game queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByHomeScore orders the results by the homeScore field.
func ByHomeScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHomeScore, opts...).ToFunc()
}

// ByAwayScore orders the results by the awayScore field.
func ByAwayScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAwayScore, opts...).ToFunc()
}

// ByAwayTeamField orders the results by awayTeam field.
func ByAwayTeamField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAwayTeamStep(), sql.OrderByField(field, opts...))
	}
}

// ByHomeTeamField orders the results by homeTeam field.
func ByHomeTeamField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHomeTeamStep(), sql.OrderByField(field, opts...))
	}
}

// BySkaterStatsCount orders the results by skaterStats count.
func BySkaterStatsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSkaterStatsStep(), opts...)
	}
}

// BySkaterStats orders the results by skaterStats terms.
func BySkaterStats(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSkaterStatsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGoalieStatsCount orders the results by goalieStats count.
func ByGoalieStatsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGoalieStatsStep(), opts...)
	}
}

// ByGoalieStats orders the results by goalieStats terms.
func ByGoalieStats(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGoalieStatsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAwayTeamStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AwayTeamInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AwayTeamTable, AwayTeamColumn),
	)
}
func newHomeTeamStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HomeTeamInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, HomeTeamTable, HomeTeamColumn),
	)
}
func newSkaterStatsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SkaterStatsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SkaterStatsTable, SkaterStatsColumn),
	)
}
func newGoalieStatsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GoalieStatsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, GoalieStatsTable, GoalieStatsPrimaryKey...),
	)
}
