// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Entry is the predicate function for entry builders.
type Entry func(*sql.Selector)

// League is the predicate function for league builders.
type League func(*sql.Selector)

// Player is the predicate function for player builders.
type Player func(*sql.Selector)

// Team is the predicate function for team builders.
type Team func(*sql.Selector)
