// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rj-davidson/stanley-cup-fantasy-hockey/db/ent/goaliestats"
	"github.com/rj-davidson/stanley-cup-fantasy-hockey/db/ent/predicate"
)

// GoalieStatsDelete is the builder for deleting a GoalieStats entity.
type GoalieStatsDelete struct {
	config
	hooks    []Hook
	mutation *GoalieStatsMutation
}

// Where appends a list predicates to the GoalieStatsDelete builder.
func (gsd *GoalieStatsDelete) Where(ps ...predicate.GoalieStats) *GoalieStatsDelete {
	gsd.mutation.Where(ps...)
	return gsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gsd *GoalieStatsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, gsd.sqlExec, gsd.mutation, gsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (gsd *GoalieStatsDelete) ExecX(ctx context.Context) int {
	n, err := gsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gsd *GoalieStatsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(goaliestats.Table, sqlgraph.NewFieldSpec(goaliestats.FieldID, field.TypeInt))
	if ps := gsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, gsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	gsd.mutation.done = true
	return affected, err
}

// GoalieStatsDeleteOne is the builder for deleting a single GoalieStats entity.
type GoalieStatsDeleteOne struct {
	gsd *GoalieStatsDelete
}

// Where appends a list predicates to the GoalieStatsDelete builder.
func (gsdo *GoalieStatsDeleteOne) Where(ps ...predicate.GoalieStats) *GoalieStatsDeleteOne {
	gsdo.gsd.mutation.Where(ps...)
	return gsdo
}

// Exec executes the deletion query.
func (gsdo *GoalieStatsDeleteOne) Exec(ctx context.Context) error {
	n, err := gsdo.gsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{goaliestats.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gsdo *GoalieStatsDeleteOne) ExecX(ctx context.Context) {
	if err := gsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
