// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rj-davidson/stanley-cup-fantasy-hockey/db/ent/entry"
	"github.com/rj-davidson/stanley-cup-fantasy-hockey/db/ent/game"
	"github.com/rj-davidson/stanley-cup-fantasy-hockey/db/ent/player"
	"github.com/rj-davidson/stanley-cup-fantasy-hockey/db/ent/predicate"
	"github.com/rj-davidson/stanley-cup-fantasy-hockey/db/ent/team"
)

// PlayerUpdate is the builder for updating Player entities.
type PlayerUpdate struct {
	config
	hooks    []Hook
	mutation *PlayerMutation
}

// Where appends a list predicates to the PlayerUpdate builder.
func (pu *PlayerUpdate) Where(ps ...predicate.Player) *PlayerUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetName sets the "name" field.
func (pu *PlayerUpdate) SetName(s string) *PlayerUpdate {
	pu.mutation.SetName(s)
	return pu
}

// SetPosition sets the "position" field.
func (pu *PlayerUpdate) SetPosition(pl player.Position) *PlayerUpdate {
	pu.mutation.SetPosition(pl)
	return pu
}

// SetGoals sets the "goals" field.
func (pu *PlayerUpdate) SetGoals(i int) *PlayerUpdate {
	pu.mutation.ResetGoals()
	pu.mutation.SetGoals(i)
	return pu
}

// AddGoals adds i to the "goals" field.
func (pu *PlayerUpdate) AddGoals(i int) *PlayerUpdate {
	pu.mutation.AddGoals(i)
	return pu
}

// SetAssists sets the "assists" field.
func (pu *PlayerUpdate) SetAssists(i int) *PlayerUpdate {
	pu.mutation.ResetAssists()
	pu.mutation.SetAssists(i)
	return pu
}

// AddAssists adds i to the "assists" field.
func (pu *PlayerUpdate) AddAssists(i int) *PlayerUpdate {
	pu.mutation.AddAssists(i)
	return pu
}

// SetShutouts sets the "shutouts" field.
func (pu *PlayerUpdate) SetShutouts(i int) *PlayerUpdate {
	pu.mutation.ResetShutouts()
	pu.mutation.SetShutouts(i)
	return pu
}

// AddShutouts adds i to the "shutouts" field.
func (pu *PlayerUpdate) AddShutouts(i int) *PlayerUpdate {
	pu.mutation.AddShutouts(i)
	return pu
}

// SetWins sets the "wins" field.
func (pu *PlayerUpdate) SetWins(i int) *PlayerUpdate {
	pu.mutation.ResetWins()
	pu.mutation.SetWins(i)
	return pu
}

// AddWins adds i to the "wins" field.
func (pu *PlayerUpdate) AddWins(i int) *PlayerUpdate {
	pu.mutation.AddWins(i)
	return pu
}

// SetTeamID sets the "team" edge to the Team entity by ID.
func (pu *PlayerUpdate) SetTeamID(id int) *PlayerUpdate {
	pu.mutation.SetTeamID(id)
	return pu
}

// SetNillableTeamID sets the "team" edge to the Team entity by ID if the given value is not nil.
func (pu *PlayerUpdate) SetNillableTeamID(id *int) *PlayerUpdate {
	if id != nil {
		pu = pu.SetTeamID(*id)
	}
	return pu
}

// SetTeam sets the "team" edge to the Team entity.
func (pu *PlayerUpdate) SetTeam(t *Team) *PlayerUpdate {
	return pu.SetTeamID(t.ID)
}

// AddEntryIDs adds the "entries" edge to the Entry entity by IDs.
func (pu *PlayerUpdate) AddEntryIDs(ids ...int) *PlayerUpdate {
	pu.mutation.AddEntryIDs(ids...)
	return pu
}

// AddEntries adds the "entries" edges to the Entry entity.
func (pu *PlayerUpdate) AddEntries(e ...*Entry) *PlayerUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return pu.AddEntryIDs(ids...)
}

// AddHomeGamesAsGoalieIDs adds the "homeGamesAsGoalie" edge to the Game entity by IDs.
func (pu *PlayerUpdate) AddHomeGamesAsGoalieIDs(ids ...int) *PlayerUpdate {
	pu.mutation.AddHomeGamesAsGoalieIDs(ids...)
	return pu
}

// AddHomeGamesAsGoalie adds the "homeGamesAsGoalie" edges to the Game entity.
func (pu *PlayerUpdate) AddHomeGamesAsGoalie(g ...*Game) *PlayerUpdate {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return pu.AddHomeGamesAsGoalieIDs(ids...)
}

// AddAwayGamesAsGoalieIDs adds the "awayGamesAsGoalie" edge to the Game entity by IDs.
func (pu *PlayerUpdate) AddAwayGamesAsGoalieIDs(ids ...int) *PlayerUpdate {
	pu.mutation.AddAwayGamesAsGoalieIDs(ids...)
	return pu
}

// AddAwayGamesAsGoalie adds the "awayGamesAsGoalie" edges to the Game entity.
func (pu *PlayerUpdate) AddAwayGamesAsGoalie(g ...*Game) *PlayerUpdate {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return pu.AddAwayGamesAsGoalieIDs(ids...)
}

// Mutation returns the PlayerMutation object of the builder.
func (pu *PlayerUpdate) Mutation() *PlayerMutation {
	return pu.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (pu *PlayerUpdate) ClearTeam() *PlayerUpdate {
	pu.mutation.ClearTeam()
	return pu
}

// ClearEntries clears all "entries" edges to the Entry entity.
func (pu *PlayerUpdate) ClearEntries() *PlayerUpdate {
	pu.mutation.ClearEntries()
	return pu
}

// RemoveEntryIDs removes the "entries" edge to Entry entities by IDs.
func (pu *PlayerUpdate) RemoveEntryIDs(ids ...int) *PlayerUpdate {
	pu.mutation.RemoveEntryIDs(ids...)
	return pu
}

// RemoveEntries removes "entries" edges to Entry entities.
func (pu *PlayerUpdate) RemoveEntries(e ...*Entry) *PlayerUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return pu.RemoveEntryIDs(ids...)
}

// ClearHomeGamesAsGoalie clears all "homeGamesAsGoalie" edges to the Game entity.
func (pu *PlayerUpdate) ClearHomeGamesAsGoalie() *PlayerUpdate {
	pu.mutation.ClearHomeGamesAsGoalie()
	return pu
}

// RemoveHomeGamesAsGoalieIDs removes the "homeGamesAsGoalie" edge to Game entities by IDs.
func (pu *PlayerUpdate) RemoveHomeGamesAsGoalieIDs(ids ...int) *PlayerUpdate {
	pu.mutation.RemoveHomeGamesAsGoalieIDs(ids...)
	return pu
}

// RemoveHomeGamesAsGoalie removes "homeGamesAsGoalie" edges to Game entities.
func (pu *PlayerUpdate) RemoveHomeGamesAsGoalie(g ...*Game) *PlayerUpdate {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return pu.RemoveHomeGamesAsGoalieIDs(ids...)
}

// ClearAwayGamesAsGoalie clears all "awayGamesAsGoalie" edges to the Game entity.
func (pu *PlayerUpdate) ClearAwayGamesAsGoalie() *PlayerUpdate {
	pu.mutation.ClearAwayGamesAsGoalie()
	return pu
}

// RemoveAwayGamesAsGoalieIDs removes the "awayGamesAsGoalie" edge to Game entities by IDs.
func (pu *PlayerUpdate) RemoveAwayGamesAsGoalieIDs(ids ...int) *PlayerUpdate {
	pu.mutation.RemoveAwayGamesAsGoalieIDs(ids...)
	return pu
}

// RemoveAwayGamesAsGoalie removes "awayGamesAsGoalie" edges to Game entities.
func (pu *PlayerUpdate) RemoveAwayGamesAsGoalie(g ...*Game) *PlayerUpdate {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return pu.RemoveAwayGamesAsGoalieIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PlayerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PlayerUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PlayerUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PlayerUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *PlayerUpdate) check() error {
	if v, ok := pu.mutation.Position(); ok {
		if err := player.PositionValidator(v); err != nil {
			return &ValidationError{Name: "position", err: fmt.Errorf(`ent: validator failed for field "Player.position": %w`, err)}
		}
	}
	return nil
}

func (pu *PlayerUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(player.Table, player.Columns, sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Name(); ok {
		_spec.SetField(player.FieldName, field.TypeString, value)
	}
	if value, ok := pu.mutation.Position(); ok {
		_spec.SetField(player.FieldPosition, field.TypeEnum, value)
	}
	if value, ok := pu.mutation.Goals(); ok {
		_spec.SetField(player.FieldGoals, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedGoals(); ok {
		_spec.AddField(player.FieldGoals, field.TypeInt, value)
	}
	if value, ok := pu.mutation.Assists(); ok {
		_spec.SetField(player.FieldAssists, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedAssists(); ok {
		_spec.AddField(player.FieldAssists, field.TypeInt, value)
	}
	if value, ok := pu.mutation.Shutouts(); ok {
		_spec.SetField(player.FieldShutouts, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedShutouts(); ok {
		_spec.AddField(player.FieldShutouts, field.TypeInt, value)
	}
	if value, ok := pu.mutation.Wins(); ok {
		_spec.SetField(player.FieldWins, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedWins(); ok {
		_spec.AddField(player.FieldWins, field.TypeInt, value)
	}
	if pu.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   player.TeamTable,
			Columns: []string{player.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   player.TeamTable,
			Columns: []string{player.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   player.EntriesTable,
			Columns: player.EntriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedEntriesIDs(); len(nodes) > 0 && !pu.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   player.EntriesTable,
			Columns: player.EntriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.EntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   player.EntriesTable,
			Columns: player.EntriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.HomeGamesAsGoalieCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.HomeGamesAsGoalieTable,
			Columns: []string{player.HomeGamesAsGoalieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedHomeGamesAsGoalieIDs(); len(nodes) > 0 && !pu.mutation.HomeGamesAsGoalieCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.HomeGamesAsGoalieTable,
			Columns: []string{player.HomeGamesAsGoalieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.HomeGamesAsGoalieIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.HomeGamesAsGoalieTable,
			Columns: []string{player.HomeGamesAsGoalieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.AwayGamesAsGoalieCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.AwayGamesAsGoalieTable,
			Columns: []string{player.AwayGamesAsGoalieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedAwayGamesAsGoalieIDs(); len(nodes) > 0 && !pu.mutation.AwayGamesAsGoalieCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.AwayGamesAsGoalieTable,
			Columns: []string{player.AwayGamesAsGoalieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.AwayGamesAsGoalieIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.AwayGamesAsGoalieTable,
			Columns: []string{player.AwayGamesAsGoalieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{player.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PlayerUpdateOne is the builder for updating a single Player entity.
type PlayerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlayerMutation
}

// SetName sets the "name" field.
func (puo *PlayerUpdateOne) SetName(s string) *PlayerUpdateOne {
	puo.mutation.SetName(s)
	return puo
}

// SetPosition sets the "position" field.
func (puo *PlayerUpdateOne) SetPosition(pl player.Position) *PlayerUpdateOne {
	puo.mutation.SetPosition(pl)
	return puo
}

// SetGoals sets the "goals" field.
func (puo *PlayerUpdateOne) SetGoals(i int) *PlayerUpdateOne {
	puo.mutation.ResetGoals()
	puo.mutation.SetGoals(i)
	return puo
}

// AddGoals adds i to the "goals" field.
func (puo *PlayerUpdateOne) AddGoals(i int) *PlayerUpdateOne {
	puo.mutation.AddGoals(i)
	return puo
}

// SetAssists sets the "assists" field.
func (puo *PlayerUpdateOne) SetAssists(i int) *PlayerUpdateOne {
	puo.mutation.ResetAssists()
	puo.mutation.SetAssists(i)
	return puo
}

// AddAssists adds i to the "assists" field.
func (puo *PlayerUpdateOne) AddAssists(i int) *PlayerUpdateOne {
	puo.mutation.AddAssists(i)
	return puo
}

// SetShutouts sets the "shutouts" field.
func (puo *PlayerUpdateOne) SetShutouts(i int) *PlayerUpdateOne {
	puo.mutation.ResetShutouts()
	puo.mutation.SetShutouts(i)
	return puo
}

// AddShutouts adds i to the "shutouts" field.
func (puo *PlayerUpdateOne) AddShutouts(i int) *PlayerUpdateOne {
	puo.mutation.AddShutouts(i)
	return puo
}

// SetWins sets the "wins" field.
func (puo *PlayerUpdateOne) SetWins(i int) *PlayerUpdateOne {
	puo.mutation.ResetWins()
	puo.mutation.SetWins(i)
	return puo
}

// AddWins adds i to the "wins" field.
func (puo *PlayerUpdateOne) AddWins(i int) *PlayerUpdateOne {
	puo.mutation.AddWins(i)
	return puo
}

// SetTeamID sets the "team" edge to the Team entity by ID.
func (puo *PlayerUpdateOne) SetTeamID(id int) *PlayerUpdateOne {
	puo.mutation.SetTeamID(id)
	return puo
}

// SetNillableTeamID sets the "team" edge to the Team entity by ID if the given value is not nil.
func (puo *PlayerUpdateOne) SetNillableTeamID(id *int) *PlayerUpdateOne {
	if id != nil {
		puo = puo.SetTeamID(*id)
	}
	return puo
}

// SetTeam sets the "team" edge to the Team entity.
func (puo *PlayerUpdateOne) SetTeam(t *Team) *PlayerUpdateOne {
	return puo.SetTeamID(t.ID)
}

// AddEntryIDs adds the "entries" edge to the Entry entity by IDs.
func (puo *PlayerUpdateOne) AddEntryIDs(ids ...int) *PlayerUpdateOne {
	puo.mutation.AddEntryIDs(ids...)
	return puo
}

// AddEntries adds the "entries" edges to the Entry entity.
func (puo *PlayerUpdateOne) AddEntries(e ...*Entry) *PlayerUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return puo.AddEntryIDs(ids...)
}

// AddHomeGamesAsGoalieIDs adds the "homeGamesAsGoalie" edge to the Game entity by IDs.
func (puo *PlayerUpdateOne) AddHomeGamesAsGoalieIDs(ids ...int) *PlayerUpdateOne {
	puo.mutation.AddHomeGamesAsGoalieIDs(ids...)
	return puo
}

// AddHomeGamesAsGoalie adds the "homeGamesAsGoalie" edges to the Game entity.
func (puo *PlayerUpdateOne) AddHomeGamesAsGoalie(g ...*Game) *PlayerUpdateOne {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return puo.AddHomeGamesAsGoalieIDs(ids...)
}

// AddAwayGamesAsGoalieIDs adds the "awayGamesAsGoalie" edge to the Game entity by IDs.
func (puo *PlayerUpdateOne) AddAwayGamesAsGoalieIDs(ids ...int) *PlayerUpdateOne {
	puo.mutation.AddAwayGamesAsGoalieIDs(ids...)
	return puo
}

// AddAwayGamesAsGoalie adds the "awayGamesAsGoalie" edges to the Game entity.
func (puo *PlayerUpdateOne) AddAwayGamesAsGoalie(g ...*Game) *PlayerUpdateOne {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return puo.AddAwayGamesAsGoalieIDs(ids...)
}

// Mutation returns the PlayerMutation object of the builder.
func (puo *PlayerUpdateOne) Mutation() *PlayerMutation {
	return puo.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (puo *PlayerUpdateOne) ClearTeam() *PlayerUpdateOne {
	puo.mutation.ClearTeam()
	return puo
}

// ClearEntries clears all "entries" edges to the Entry entity.
func (puo *PlayerUpdateOne) ClearEntries() *PlayerUpdateOne {
	puo.mutation.ClearEntries()
	return puo
}

// RemoveEntryIDs removes the "entries" edge to Entry entities by IDs.
func (puo *PlayerUpdateOne) RemoveEntryIDs(ids ...int) *PlayerUpdateOne {
	puo.mutation.RemoveEntryIDs(ids...)
	return puo
}

// RemoveEntries removes "entries" edges to Entry entities.
func (puo *PlayerUpdateOne) RemoveEntries(e ...*Entry) *PlayerUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return puo.RemoveEntryIDs(ids...)
}

// ClearHomeGamesAsGoalie clears all "homeGamesAsGoalie" edges to the Game entity.
func (puo *PlayerUpdateOne) ClearHomeGamesAsGoalie() *PlayerUpdateOne {
	puo.mutation.ClearHomeGamesAsGoalie()
	return puo
}

// RemoveHomeGamesAsGoalieIDs removes the "homeGamesAsGoalie" edge to Game entities by IDs.
func (puo *PlayerUpdateOne) RemoveHomeGamesAsGoalieIDs(ids ...int) *PlayerUpdateOne {
	puo.mutation.RemoveHomeGamesAsGoalieIDs(ids...)
	return puo
}

// RemoveHomeGamesAsGoalie removes "homeGamesAsGoalie" edges to Game entities.
func (puo *PlayerUpdateOne) RemoveHomeGamesAsGoalie(g ...*Game) *PlayerUpdateOne {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return puo.RemoveHomeGamesAsGoalieIDs(ids...)
}

// ClearAwayGamesAsGoalie clears all "awayGamesAsGoalie" edges to the Game entity.
func (puo *PlayerUpdateOne) ClearAwayGamesAsGoalie() *PlayerUpdateOne {
	puo.mutation.ClearAwayGamesAsGoalie()
	return puo
}

// RemoveAwayGamesAsGoalieIDs removes the "awayGamesAsGoalie" edge to Game entities by IDs.
func (puo *PlayerUpdateOne) RemoveAwayGamesAsGoalieIDs(ids ...int) *PlayerUpdateOne {
	puo.mutation.RemoveAwayGamesAsGoalieIDs(ids...)
	return puo
}

// RemoveAwayGamesAsGoalie removes "awayGamesAsGoalie" edges to Game entities.
func (puo *PlayerUpdateOne) RemoveAwayGamesAsGoalie(g ...*Game) *PlayerUpdateOne {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return puo.RemoveAwayGamesAsGoalieIDs(ids...)
}

// Where appends a list predicates to the PlayerUpdate builder.
func (puo *PlayerUpdateOne) Where(ps ...predicate.Player) *PlayerUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PlayerUpdateOne) Select(field string, fields ...string) *PlayerUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Player entity.
func (puo *PlayerUpdateOne) Save(ctx context.Context) (*Player, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PlayerUpdateOne) SaveX(ctx context.Context) *Player {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PlayerUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PlayerUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *PlayerUpdateOne) check() error {
	if v, ok := puo.mutation.Position(); ok {
		if err := player.PositionValidator(v); err != nil {
			return &ValidationError{Name: "position", err: fmt.Errorf(`ent: validator failed for field "Player.position": %w`, err)}
		}
	}
	return nil
}

func (puo *PlayerUpdateOne) sqlSave(ctx context.Context) (_node *Player, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(player.Table, player.Columns, sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Player.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, player.FieldID)
		for _, f := range fields {
			if !player.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != player.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Name(); ok {
		_spec.SetField(player.FieldName, field.TypeString, value)
	}
	if value, ok := puo.mutation.Position(); ok {
		_spec.SetField(player.FieldPosition, field.TypeEnum, value)
	}
	if value, ok := puo.mutation.Goals(); ok {
		_spec.SetField(player.FieldGoals, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedGoals(); ok {
		_spec.AddField(player.FieldGoals, field.TypeInt, value)
	}
	if value, ok := puo.mutation.Assists(); ok {
		_spec.SetField(player.FieldAssists, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedAssists(); ok {
		_spec.AddField(player.FieldAssists, field.TypeInt, value)
	}
	if value, ok := puo.mutation.Shutouts(); ok {
		_spec.SetField(player.FieldShutouts, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedShutouts(); ok {
		_spec.AddField(player.FieldShutouts, field.TypeInt, value)
	}
	if value, ok := puo.mutation.Wins(); ok {
		_spec.SetField(player.FieldWins, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedWins(); ok {
		_spec.AddField(player.FieldWins, field.TypeInt, value)
	}
	if puo.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   player.TeamTable,
			Columns: []string{player.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   player.TeamTable,
			Columns: []string{player.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   player.EntriesTable,
			Columns: player.EntriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedEntriesIDs(); len(nodes) > 0 && !puo.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   player.EntriesTable,
			Columns: player.EntriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.EntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   player.EntriesTable,
			Columns: player.EntriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.HomeGamesAsGoalieCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.HomeGamesAsGoalieTable,
			Columns: []string{player.HomeGamesAsGoalieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedHomeGamesAsGoalieIDs(); len(nodes) > 0 && !puo.mutation.HomeGamesAsGoalieCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.HomeGamesAsGoalieTable,
			Columns: []string{player.HomeGamesAsGoalieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.HomeGamesAsGoalieIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.HomeGamesAsGoalieTable,
			Columns: []string{player.HomeGamesAsGoalieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.AwayGamesAsGoalieCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.AwayGamesAsGoalieTable,
			Columns: []string{player.AwayGamesAsGoalieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedAwayGamesAsGoalieIDs(); len(nodes) > 0 && !puo.mutation.AwayGamesAsGoalieCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.AwayGamesAsGoalieTable,
			Columns: []string{player.AwayGamesAsGoalieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.AwayGamesAsGoalieIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.AwayGamesAsGoalieTable,
			Columns: []string{player.AwayGamesAsGoalieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Player{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{player.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
