// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/rj-davidson/stanley-cup-fantasy-hockey/db/ent/schema"
	"github.com/rj-davidson/stanley-cup-fantasy-hockey/db/ent/team"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	teamFields := schema.Team{}.Fields()
	_ = teamFields
	// teamDescEliminated is the schema descriptor for eliminated field.
	teamDescEliminated := teamFields[2].Descriptor()
	// team.DefaultEliminated holds the default value on creation for the eliminated field.
	team.DefaultEliminated = teamDescEliminated.Default.(bool)
}
