version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: ["./main", "-init-data"]
    ports:
      - '8080:8080'

  client:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
