// Code generated by ent, DO NOT EDIT.

package stats

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/rj-davidson/stanley-cup-fantasy-hockey/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Stats {
	return predicate.Stats(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Stats {
	return predicate.Stats(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Stats {
	return predicate.Stats(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Stats {
	return predicate.Stats(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Stats {
	return predicate.Stats(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Stats {
	return predicate.Stats(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Stats {
	return predicate.Stats(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Stats {
	return predicate.Stats(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Stats {
	return predicate.Stats(sql.FieldLTE(FieldID, id))
}

// Goals applies equality check predicate on the "goals" field. It's identical to GoalsEQ.
func Goals(v int) predicate.Stats {
	return predicate.Stats(sql.FieldEQ(FieldGoals, v))
}

// Assists applies equality check predicate on the "assists" field. It's identical to AssistsEQ.
func Assists(v int) predicate.Stats {
	return predicate.Stats(sql.FieldEQ(FieldAssists, v))
}

// Shutouts applies equality check predicate on the "shutouts" field. It's identical to ShutoutsEQ.
func Shutouts(v int) predicate.Stats {
	return predicate.Stats(sql.FieldEQ(FieldShutouts, v))
}

// Wins applies equality check predicate on the "wins" field. It's identical to WinsEQ.
func Wins(v int) predicate.Stats {
	return predicate.Stats(sql.FieldEQ(FieldWins, v))
}

// GoalsEQ applies the EQ predicate on the "goals" field.
func GoalsEQ(v int) predicate.Stats {
	return predicate.Stats(sql.FieldEQ(FieldGoals, v))
}

// GoalsNEQ applies the NEQ predicate on the "goals" field.
func GoalsNEQ(v int) predicate.Stats {
	return predicate.Stats(sql.FieldNEQ(FieldGoals, v))
}

// GoalsIn applies the In predicate on the "goals" field.
func GoalsIn(vs ...int) predicate.Stats {
	return predicate.Stats(sql.FieldIn(FieldGoals, vs...))
}

// GoalsNotIn applies the NotIn predicate on the "goals" field.
func GoalsNotIn(vs ...int) predicate.Stats {
	return predicate.Stats(sql.FieldNotIn(FieldGoals, vs...))
}

// GoalsGT applies the GT predicate on the "goals" field.
func GoalsGT(v int) predicate.Stats {
	return predicate.Stats(sql.FieldGT(FieldGoals, v))
}

// GoalsGTE applies the GTE predicate on the "goals" field.
func GoalsGTE(v int) predicate.Stats {
	return predicate.Stats(sql.FieldGTE(FieldGoals, v))
}

// GoalsLT applies the LT predicate on the "goals" field.
func GoalsLT(v int) predicate.Stats {
	return predicate.Stats(sql.FieldLT(FieldGoals, v))
}

// GoalsLTE applies the LTE predicate on the "goals" field.
func GoalsLTE(v int) predicate.Stats {
	return predicate.Stats(sql.FieldLTE(FieldGoals, v))
}

// AssistsEQ applies the EQ predicate on the "assists" field.
func AssistsEQ(v int) predicate.Stats {
	return predicate.Stats(sql.FieldEQ(FieldAssists, v))
}

// AssistsNEQ applies the NEQ predicate on the "assists" field.
func AssistsNEQ(v int) predicate.Stats {
	return predicate.Stats(sql.FieldNEQ(FieldAssists, v))
}

// AssistsIn applies the In predicate on the "assists" field.
func AssistsIn(vs ...int) predicate.Stats {
	return predicate.Stats(sql.FieldIn(FieldAssists, vs...))
}

// AssistsNotIn applies the NotIn predicate on the "assists" field.
func AssistsNotIn(vs ...int) predicate.Stats {
	return predicate.Stats(sql.FieldNotIn(FieldAssists, vs...))
}

// AssistsGT applies the GT predicate on the "assists" field.
func AssistsGT(v int) predicate.Stats {
	return predicate.Stats(sql.FieldGT(FieldAssists, v))
}

// AssistsGTE applies the GTE predicate on the "assists" field.
func AssistsGTE(v int) predicate.Stats {
	return predicate.Stats(sql.FieldGTE(FieldAssists, v))
}

// AssistsLT applies the LT predicate on the "assists" field.
func AssistsLT(v int) predicate.Stats {
	return predicate.Stats(sql.FieldLT(FieldAssists, v))
}

// AssistsLTE applies the LTE predicate on the "assists" field.
func AssistsLTE(v int) predicate.Stats {
	return predicate.Stats(sql.FieldLTE(FieldAssists, v))
}

// ShutoutsEQ applies the EQ predicate on the "shutouts" field.
func ShutoutsEQ(v int) predicate.Stats {
	return predicate.Stats(sql.FieldEQ(FieldShutouts, v))
}

// ShutoutsNEQ applies the NEQ predicate on the "shutouts" field.
func ShutoutsNEQ(v int) predicate.Stats {
	return predicate.Stats(sql.FieldNEQ(FieldShutouts, v))
}

// ShutoutsIn applies the In predicate on the "shutouts" field.
func ShutoutsIn(vs ...int) predicate.Stats {
	return predicate.Stats(sql.FieldIn(FieldShutouts, vs...))
}

// ShutoutsNotIn applies the NotIn predicate on the "shutouts" field.
func ShutoutsNotIn(vs ...int) predicate.Stats {
	return predicate.Stats(sql.FieldNotIn(FieldShutouts, vs...))
}

// ShutoutsGT applies the GT predicate on the "shutouts" field.
func ShutoutsGT(v int) predicate.Stats {
	return predicate.Stats(sql.FieldGT(FieldShutouts, v))
}

// ShutoutsGTE applies the GTE predicate on the "shutouts" field.
func ShutoutsGTE(v int) predicate.Stats {
	return predicate.Stats(sql.FieldGTE(FieldShutouts, v))
}

// ShutoutsLT applies the LT predicate on the "shutouts" field.
func ShutoutsLT(v int) predicate.Stats {
	return predicate.Stats(sql.FieldLT(FieldShutouts, v))
}

// ShutoutsLTE applies the LTE predicate on the "shutouts" field.
func ShutoutsLTE(v int) predicate.Stats {
	return predicate.Stats(sql.FieldLTE(FieldShutouts, v))
}

// WinsEQ applies the EQ predicate on the "wins" field.
func WinsEQ(v int) predicate.Stats {
	return predicate.Stats(sql.FieldEQ(FieldWins, v))
}

// WinsNEQ applies the NEQ predicate on the "wins" field.
func WinsNEQ(v int) predicate.Stats {
	return predicate.Stats(sql.FieldNEQ(FieldWins, v))
}

// WinsIn applies the In predicate on the "wins" field.
func WinsIn(vs ...int) predicate.Stats {
	return predicate.Stats(sql.FieldIn(FieldWins, vs...))
}

// WinsNotIn applies the NotIn predicate on the "wins" field.
func WinsNotIn(vs ...int) predicate.Stats {
	return predicate.Stats(sql.FieldNotIn(FieldWins, vs...))
}

// WinsGT applies the GT predicate on the "wins" field.
func WinsGT(v int) predicate.Stats {
	return predicate.Stats(sql.FieldGT(FieldWins, v))
}

// WinsGTE applies the GTE predicate on the "wins" field.
func WinsGTE(v int) predicate.Stats {
	return predicate.Stats(sql.FieldGTE(FieldWins, v))
}

// WinsLT applies the LT predicate on the "wins" field.
func WinsLT(v int) predicate.Stats {
	return predicate.Stats(sql.FieldLT(FieldWins, v))
}

// WinsLTE applies the LTE predicate on the "wins" field.
func WinsLTE(v int) predicate.Stats {
	return predicate.Stats(sql.FieldLTE(FieldWins, v))
}

// HasPlayer applies the HasEdge predicate on the "player" edge.
func HasPlayer() predicate.Stats {
	return predicate.Stats(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, PlayerTable, PlayerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlayerWith applies the HasEdge predicate on the "player" edge with a given conditions (other predicates).
func HasPlayerWith(preds ...predicate.Player) predicate.Stats {
	return predicate.Stats(func(s *sql.Selector) {
		step := newPlayerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Stats) predicate.Stats {
	return predicate.Stats(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Stats) predicate.Stats {
	return predicate.Stats(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Stats) predicate.Stats {
	return predicate.Stats(func(s *sql.Selector) {
		p(s.Not())
	})
}
