// Code generated by ent, DO NOT EDIT.

package league

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/rj-davidson/stanley-cup-fantasy-hockey/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.League {
	return predicate.League(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.League {
	return predicate.League(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.League {
	return predicate.League(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.League {
	return predicate.League(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.League {
	return predicate.League(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.League {
	return predicate.League(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.League {
	return predicate.League(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.League {
	return predicate.League(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.League {
	return predicate.League(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.League {
	return predicate.League(sql.FieldEQ(FieldName, v))
}

// Season applies equality check predicate on the "season" field. It's identical to SeasonEQ.
func Season(v int) predicate.League {
	return predicate.League(sql.FieldEQ(FieldSeason, v))
}

// Public applies equality check predicate on the "public" field. It's identical to PublicEQ.
func Public(v bool) predicate.League {
	return predicate.League(sql.FieldEQ(FieldPublic, v))
}

// NumForwards applies equality check predicate on the "num_forwards" field. It's identical to NumForwardsEQ.
func NumForwards(v int) predicate.League {
	return predicate.League(sql.FieldEQ(FieldNumForwards, v))
}

// NumDefenders applies equality check predicate on the "num_defenders" field. It's identical to NumDefendersEQ.
func NumDefenders(v int) predicate.League {
	return predicate.League(sql.FieldEQ(FieldNumDefenders, v))
}

// NumGoalies applies equality check predicate on the "num_goalies" field. It's identical to NumGoaliesEQ.
func NumGoalies(v int) predicate.League {
	return predicate.League(sql.FieldEQ(FieldNumGoalies, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.League {
	return predicate.League(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.League {
	return predicate.League(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.League {
	return predicate.League(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.League {
	return predicate.League(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.League {
	return predicate.League(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.League {
	return predicate.League(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.League {
	return predicate.League(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.League {
	return predicate.League(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.League {
	return predicate.League(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.League {
	return predicate.League(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.League {
	return predicate.League(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.League {
	return predicate.League(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.League {
	return predicate.League(sql.FieldContainsFold(FieldName, v))
}

// SeasonEQ applies the EQ predicate on the "season" field.
func SeasonEQ(v int) predicate.League {
	return predicate.League(sql.FieldEQ(FieldSeason, v))
}

// SeasonNEQ applies the NEQ predicate on the "season" field.
func SeasonNEQ(v int) predicate.League {
	return predicate.League(sql.FieldNEQ(FieldSeason, v))
}

// SeasonIn applies the In predicate on the "season" field.
func SeasonIn(vs ...int) predicate.League {
	return predicate.League(sql.FieldIn(FieldSeason, vs...))
}

// SeasonNotIn applies the NotIn predicate on the "season" field.
func SeasonNotIn(vs ...int) predicate.League {
	return predicate.League(sql.FieldNotIn(FieldSeason, vs...))
}

// SeasonGT applies the GT predicate on the "season" field.
func SeasonGT(v int) predicate.League {
	return predicate.League(sql.FieldGT(FieldSeason, v))
}

// SeasonGTE applies the GTE predicate on the "season" field.
func SeasonGTE(v int) predicate.League {
	return predicate.League(sql.FieldGTE(FieldSeason, v))
}

// SeasonLT applies the LT predicate on the "season" field.
func SeasonLT(v int) predicate.League {
	return predicate.League(sql.FieldLT(FieldSeason, v))
}

// SeasonLTE applies the LTE predicate on the "season" field.
func SeasonLTE(v int) predicate.League {
	return predicate.League(sql.FieldLTE(FieldSeason, v))
}

// PublicEQ applies the EQ predicate on the "public" field.
func PublicEQ(v bool) predicate.League {
	return predicate.League(sql.FieldEQ(FieldPublic, v))
}

// PublicNEQ applies the NEQ predicate on the "public" field.
func PublicNEQ(v bool) predicate.League {
	return predicate.League(sql.FieldNEQ(FieldPublic, v))
}

// NumForwardsEQ applies the EQ predicate on the "num_forwards" field.
func NumForwardsEQ(v int) predicate.League {
	return predicate.League(sql.FieldEQ(FieldNumForwards, v))
}

// NumForwardsNEQ applies the NEQ predicate on the "num_forwards" field.
func NumForwardsNEQ(v int) predicate.League {
	return predicate.League(sql.FieldNEQ(FieldNumForwards, v))
}

// NumForwardsIn applies the In predicate on the "num_forwards" field.
func NumForwardsIn(vs ...int) predicate.League {
	return predicate.League(sql.FieldIn(FieldNumForwards, vs...))
}

// NumForwardsNotIn applies the NotIn predicate on the "num_forwards" field.
func NumForwardsNotIn(vs ...int) predicate.League {
	return predicate.League(sql.FieldNotIn(FieldNumForwards, vs...))
}

// NumForwardsGT applies the GT predicate on the "num_forwards" field.
func NumForwardsGT(v int) predicate.League {
	return predicate.League(sql.FieldGT(FieldNumForwards, v))
}

// NumForwardsGTE applies the GTE predicate on the "num_forwards" field.
func NumForwardsGTE(v int) predicate.League {
	return predicate.League(sql.FieldGTE(FieldNumForwards, v))
}

// NumForwardsLT applies the LT predicate on the "num_forwards" field.
func NumForwardsLT(v int) predicate.League {
	return predicate.League(sql.FieldLT(FieldNumForwards, v))
}

// NumForwardsLTE applies the LTE predicate on the "num_forwards" field.
func NumForwardsLTE(v int) predicate.League {
	return predicate.League(sql.FieldLTE(FieldNumForwards, v))
}

// NumDefendersEQ applies the EQ predicate on the "num_defenders" field.
func NumDefendersEQ(v int) predicate.League {
	return predicate.League(sql.FieldEQ(FieldNumDefenders, v))
}

// NumDefendersNEQ applies the NEQ predicate on the "num_defenders" field.
func NumDefendersNEQ(v int) predicate.League {
	return predicate.League(sql.FieldNEQ(FieldNumDefenders, v))
}

// NumDefendersIn applies the In predicate on the "num_defenders" field.
func NumDefendersIn(vs ...int) predicate.League {
	return predicate.League(sql.FieldIn(FieldNumDefenders, vs...))
}

// NumDefendersNotIn applies the NotIn predicate on the "num_defenders" field.
func NumDefendersNotIn(vs ...int) predicate.League {
	return predicate.League(sql.FieldNotIn(FieldNumDefenders, vs...))
}

// NumDefendersGT applies the GT predicate on the "num_defenders" field.
func NumDefendersGT(v int) predicate.League {
	return predicate.League(sql.FieldGT(FieldNumDefenders, v))
}

// NumDefendersGTE applies the GTE predicate on the "num_defenders" field.
func NumDefendersGTE(v int) predicate.League {
	return predicate.League(sql.FieldGTE(FieldNumDefenders, v))
}

// NumDefendersLT applies the LT predicate on the "num_defenders" field.
func NumDefendersLT(v int) predicate.League {
	return predicate.League(sql.FieldLT(FieldNumDefenders, v))
}

// NumDefendersLTE applies the LTE predicate on the "num_defenders" field.
func NumDefendersLTE(v int) predicate.League {
	return predicate.League(sql.FieldLTE(FieldNumDefenders, v))
}

// NumGoaliesEQ applies the EQ predicate on the "num_goalies" field.
func NumGoaliesEQ(v int) predicate.League {
	return predicate.League(sql.FieldEQ(FieldNumGoalies, v))
}

// NumGoaliesNEQ applies the NEQ predicate on the "num_goalies" field.
func NumGoaliesNEQ(v int) predicate.League {
	return predicate.League(sql.FieldNEQ(FieldNumGoalies, v))
}

// NumGoaliesIn applies the In predicate on the "num_goalies" field.
func NumGoaliesIn(vs ...int) predicate.League {
	return predicate.League(sql.FieldIn(FieldNumGoalies, vs...))
}

// NumGoaliesNotIn applies the NotIn predicate on the "num_goalies" field.
func NumGoaliesNotIn(vs ...int) predicate.League {
	return predicate.League(sql.FieldNotIn(FieldNumGoalies, vs...))
}

// NumGoaliesGT applies the GT predicate on the "num_goalies" field.
func NumGoaliesGT(v int) predicate.League {
	return predicate.League(sql.FieldGT(FieldNumGoalies, v))
}

// NumGoaliesGTE applies the GTE predicate on the "num_goalies" field.
func NumGoaliesGTE(v int) predicate.League {
	return predicate.League(sql.FieldGTE(FieldNumGoalies, v))
}

// NumGoaliesLT applies the LT predicate on the "num_goalies" field.
func NumGoaliesLT(v int) predicate.League {
	return predicate.League(sql.FieldLT(FieldNumGoalies, v))
}

// NumGoaliesLTE applies the LTE predicate on the "num_goalies" field.
func NumGoaliesLTE(v int) predicate.League {
	return predicate.League(sql.FieldLTE(FieldNumGoalies, v))
}

// HasEntries applies the HasEdge predicate on the "entries" edge.
func HasEntries() predicate.League {
	return predicate.League(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EntriesTable, EntriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEntriesWith applies the HasEdge predicate on the "entries" edge with a given conditions (other predicates).
func HasEntriesWith(preds ...predicate.Entry) predicate.League {
	return predicate.League(func(s *sql.Selector) {
		step := newEntriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.League) predicate.League {
	return predicate.League(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.League) predicate.League {
	return predicate.League(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.League) predicate.League {
	return predicate.League(func(s *sql.Selector) {
		p(s.Not())
	})
}
